# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install pnpm globally
RUN npm install -g pnpm

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

# Copy the rest of the source code
COPY . .

# Build the project
RUN pnpm run build

# Expose port if needed (optional, MCP uses stdio by default)
# EXPOSE 3000

# Run the MCP server
CMD ["node", "dist/index.js"]
